server:
  port: 8080
spring:
  application:
    name: covid

#  TODO: colocar os valores em variaveis da aplicação!
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/planisa
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true


client:
  ninja-api:
    url: https://api.api-ninjas.com/v1/covid19
    token:
      header:
        key: fN3J9qNcKgds/6cZAfp2lg==GnXLeJ4csLkVLs9G

